### PR TITLE
Migrate to v2.0 and correct examples

### PR DESCRIPTION
**Pull request by ScruffR**
I've done the migration to v2.0 libraries format and also adjusted the original samples to also build for Particle.

### CODE REVIEW

**Comment by tomdeboer** [comment]
I will manually merge this tomorrow.

**Comment by cliffmcc** [comment]
Could someone please merge these changes upload them to the Particle ecosystem?

**Comment by GregSawin** [comment]
Please merge.  It's a pain having to manually include these libraries in my Particle projects and the other working libraries lack many of the features of this one.

**Comment by tomdeboer** [comment]
I merged

**Comment by ScruffR** [comment]
@tomdeboer, can you also upload this new version to the Particle libs repository?

**Pull request closed without merging**
